config/routes.rb
Rails.application.routes.draw do
  resources :carts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :exchange_rates
  resources :menu_photos
  resources :restaurants do
    resources :categories
    resources :menus
  end
  resources :currency_maps
  resources :language_maps
  resources :languages
  resources :restaurant_photos
  
  root 'restaurants#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :menu
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menus, dependent: :destroy
	belongs_to :restaurant

	def translation_category(locale)
		language_map = LanguageMap.find_by language_id: self.name_id, code: locale
		if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
	end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :menus
	has_many :exchange_maps, dependent: :destroy

	DEFAULT_EXCHANGES = "KRW"

	EXCHANGES = {
		"KRW" => "₩",
		"USD" => "$",
		"JPY" => "¥",
		"CNY" => "Y"
	}
end

app/models/currency_map.rb
class CurrencyMap < ActiveRecord::Base
  belongs_to :language
end

app/models/exchange_map.rb
class ExchangeMap < ActiveRecord::Base
	belongs_to :currency
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base

	def calculate(exchange_rate)
			exchangeRates = ExchangeRate.all
			krw_rate = exchangeRates.find_by(key: "KRW")
			usd_rate = exchangeRates.find_by(key: "USD")
			jpy_rate = exchangeRates.find_by(key: "JPW")
			cny_rate = exchangeRates.find_by(key: "CNY")

	end
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :language_maps, dependent: :destroy
	has_many :menus

	DEFAULT_LANGUAGE = "ko"
	
	LANGUAGES = {
		"ko" => "한국어",
		"en" => "English",
		"jp" => "日本語",
		"cn" => "中文"
	}

end

app/models/language_map.rb
class LanguageMap < ActiveRecord::Base
  belongs_to :language
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :category
  belongs_to :language
  belongs_to :currency
  belongs_to :restaurant
  has_many :menu_photos, dependent: :destroy
  has_many :carts

  def translation_name(locale)
  	language_map = self.language.language_maps.find_by_code(locale)
  	
  	if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
  end

  def translation_desc(locale)
    language_map = LanguageMap.find_by language_id: self.desc_id, code: locale
    
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def change_price(locale)
    exchange_map = ExchangeMap.find_by currency_id: self.currency_id, currency_code: locale
    if !exchange_map.nil?
      exchange_map.price
    else
      ""
    end
  end

  def translation_category(locale)
    if !self.category_id.nil?
      category = Category.find(self.category_id).name_id
      language_map = LanguageMap.find_by language_id: category, code: locale
    else
      ""
    end
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def get_mphoto
    mphoto = MenuPhoto.find_by menu_id: self.id
    if !mphoto.nil?
      mphoto.avatar.url(:medium)
    else
      "http://placehold.it/350x150?text=no+image"
    end
  end

end

app/models/menu_photo.rb
class MenuPhoto < ActiveRecord::Base
  belongs_to :menu

  has_attached_file :avatar,
   styles: { medium: "350x150>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :categories, dependent: :destroy
	has_many :restaurant_photos, dependent: :destroy

	def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/restaurant_photo.rb
class RestaurantPhoto < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :avatar,
   styles: { medium: "600x300>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/currency_maps_controller.rb
class CurrencyMapsController < ApplicationController
  before_action :set_currency_map, only: [:show, :edit, :update, :destroy]

  # GET /currency_maps
  # GET /currency_maps.json
  def index
    @currency_maps = CurrencyMap.all
  end

  # GET /currency_maps/1
  # GET /currency_maps/1.json
  def show
  end

  # GET /currency_maps/new
  def new
    @currency_map = CurrencyMap.new
  end

  # GET /currency_maps/1/edit
  def edit
  end

  # POST /currency_maps
  # POST /currency_maps.json
  def create
    @currency_map = CurrencyMap.new(currency_map_params)

    respond_to do |format|
      if @currency_map.save
        format.html { redirect_to @currency_map, notice: 'Currency map was successfully created.' }
        format.json { render :show, status: :created, location: @currency_map }
      else
        format.html { render :new }
        format.json { render json: @currency_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currency_maps/1
  # PATCH/PUT /currency_maps/1.json
  def update
    respond_to do |format|
      if @currency_map.update(currency_map_params)
        format.html { redirect_to @currency_map, notice: 'Currency map was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency_map }
      else
        format.html { render :edit }
        format.json { render json: @currency_map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currency_maps/1
  # DELETE /currency_maps/1.json
  def destroy
    @currency_map.destroy
    respond_to do |format|
      format.html { redirect_to currency_maps_url, notice: 'Currency map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency_map
      @currency_map = CurrencyMap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_map_params
      params.require(:currency_map).permit(:language_id, :language_code, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/currency_maps_helper.rb
module CurrencyMapsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/menu_photos_helper.rb
module MenuPhotosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/currency_maps/_form.html.erb
<%= form_for(@currency_map) do |f| %>
  <% if @currency_map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency_map.errors.count, "error") %> prohibited this currency_map from being saved:</h2>

      <ul>
      <% @currency_map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language_id %><br>
    <%= f.text_field :language_id %>
  </div>
  <div class="field">
    <%= f.label :language_code %><br>
    <%= f.text_field :language_code %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currency_maps/edit.html.erb
<h1>Editing Currency Map</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency_map %> |
<%= link_to 'Back', currency_maps_path %>

app/views/currency_maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Currency Maps</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>Language code</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @currency_maps.each do |currency_map| %>
      <tr>
        <td><%= currency_map.language %></td>
        <td><%= currency_map.language_code %></td>
        <td><%= currency_map.price %></td>
        <td><%= link_to 'Show', currency_map %></td>
        <td><%= link_to 'Edit', edit_currency_map_path(currency_map) %></td>
        <td><%= link_to 'Destroy', currency_map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Currency map', new_currency_map_path %>

app/views/currency_maps/new.html.erb
<h1>New Currency Map</h1>

<%= render 'form' %>

<%= link_to 'Back', currency_maps_path %>

app/views/currency_maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @currency_map.language %>
</p>

<p>
  <strong>Language code:</strong>
  <%= @currency_map.language_code %>
</p>

<p>
  <strong>Price:</strong>
  <%= @currency_map.price %>
</p>

<%= link_to 'Edit', edit_currency_map_path(@currency_map) %> |
<%= link_to 'Back', currency_maps_path %>