config/routes.rb
Rails.application.routes.draw do
  resources :carts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :exchange_rates
  resources :menu_photos
  resources :restaurants do
    resources :categories
    resources :menus
  end
  resources :currency_maps
  resources :language_maps
  resources :languages
  resources :restaurant_photos
  
  root 'restaurants#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :menu
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menus, dependent: :destroy
	belongs_to :restaurant

	def translation_category(locale)
		language_map = LanguageMap.find_by language_id: self.name_id, code: locale
		if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
	end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :menus
	has_many :exchange_maps, dependent: :destroy

	DEFAULT_EXCHANGES = "KRW"

	EXCHANGES = {
		"KRW" => "₩",
		"USD" => "$",
		"JPY" => "¥",
		"CNY" => "Y"
	}
end

app/models/currency_map.rb
class CurrencyMap < ActiveRecord::Base
  belongs_to :language
end

app/models/exchange_map.rb
class ExchangeMap < ActiveRecord::Base
	belongs_to :currency
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base

	def calculate(exchange_rate)
			exchangeRates = ExchangeRate.all
			krw_rate = exchangeRates.find_by(key: "KRW")
			usd_rate = exchangeRates.find_by(key: "USD")
			jpy_rate = exchangeRates.find_by(key: "JPW")
			cny_rate = exchangeRates.find_by(key: "CNY")

	end
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :language_maps, dependent: :destroy
	has_many :menus

	DEFAULT_LANGUAGE = "ko"
	
	LANGUAGES = {
		"ko" => "한국어",
		"en" => "English",
		"jp" => "日本語",
		"cn" => "中文"
	}

end

app/models/language_map.rb
class LanguageMap < ActiveRecord::Base
  belongs_to :language
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :category
  belongs_to :language
  belongs_to :currency
  belongs_to :restaurant
  has_many :menu_photos, dependent: :destroy
  has_many :carts

  def translation_name(locale)
  	language_map = self.language.language_maps.find_by_code(locale)
  	
  	if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
  end

  def translation_desc(locale)
    language_map = LanguageMap.find_by language_id: self.desc_id, code: locale
    
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def change_price(locale)
    exchange_map = ExchangeMap.find_by currency_id: self.currency_id, currency_code: locale
    if !exchange_map.nil?
      exchange_map.price
    else
      ""
    end
  end

  def translation_category(locale)
    if !self.category_id.nil?
      category = Category.find(self.category_id).name_id
      language_map = LanguageMap.find_by language_id: category, code: locale
    else
      ""
    end
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def get_mphoto
    mphoto = MenuPhoto.find_by menu_id: self.id
    if !mphoto.nil?
      mphoto.avatar.url(:medium)
    else
      "http://placehold.it/350x150?text=no+image"
    end
  end

end

app/models/menu_photo.rb
class MenuPhoto < ActiveRecord::Base
  belongs_to :menu

  has_attached_file :avatar,
   styles: { medium: "350x150>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :categories, dependent: :destroy
	has_many :restaurant_photos, dependent: :destroy

	def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/restaurant_photo.rb
class RestaurantPhoto < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :avatar,
   styles: { medium: "600x300>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
    if current_user
      @cart = Cart.find_by(user_id: current_user.id)
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @menus = @restaurant.menus.all
    @categories = @restaurant.categories.all
    @restaurant_photos = @restaurant.restaurant_photos.all
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create

    @restaurant = Restaurant.create(name: params[:restaurant][:name], address: params[:restaurant][:address],
     Rep: params[:restaurant][:Rep], phone_number: params[:restaurant][:phone_number], extra_info: params[:restaurant][:extra_info],
     open_time: params[:open_time], close_time: params[:close_time], user_id: current_user.id)

    if params[:images]
      params[:images].each { |image|
        @restaurant.restaurant_photos.create(restaurant_id: @restaurant.id, avatar: image)
      }
    end

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    rest = RestaurantPhoto.find_by restaurant_id: @restaurant.id
    user = current_user.id
    if !rest.nil?
      rest.update_column(:avatar, params[:images])
    end

    respond_to do |format|
      if @restaurant.update(name: params[:restaurant][:name], address: params[:restaurant][:address],
     Rep: params[:restaurant][:Rep], phone_number: params[:restaurant][:phone_number], extra_info: params[:restaurant][:extra_info],
     open_time: params[:open_time], close_time: params[:close_time], user_id: user)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy

    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :Rep, :phone_number, :extra_info)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/menu_photos_helper.rb
module MenuPhotosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="form-horizontal">
<%= form_for(@restaurant, html: { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="row">
    <div class="col-sm-4">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control"%>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="field">
        <%= f.label :Owner %><br>
        <%= f.text_field :Rep, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="field">
        <%= f.label :phone_number %><br>
        <%= f.text_field :phone_number, class: "form-control" %>
      </div>
    </div>
  </div>
  </div>

  <div class="form-group">
  <div class="row">
    <div class="col-sm-12">
      <div class="field">
        <%= f.label :address %><br>
        <%= f.text_field :address, class: "form-control"%>
      </div>
    </div>
  </div>
  </div>

  <div class="form-group">
  <div class="row">
    <div class="col-sm-4">
      <label for="open_time">open time</label>
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="timepicker1" name="open_time" type="text" class="form-control input-small">
        <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
      </div>
    </div>
    <script type="text/javascript">
      $('#timepicker1').timepicker();
    </script>

    <div class="col-sm-4">
      <label for="close_time">close time</label>
      <div class="input-group bootstrap-timepicker timepicker">
        <input id="timepicker2" name="close_time" type="text" class="form-control input-small">
        <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
      </div>
    </div>
    <script type="text/javascript">
    $('#timepicker2').timepicker();
  </script>
  </div>
  </div>

  <div class="form-group">
  <div class="row">
    <div class="col-sm-4">
      <div class="field">
        <%= f.label :extra_info %><br>
        <%= f.text_field :extra_info, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="field">
        <%= f.label 'Restaurant Photo' %>
        <div class="input_fields_wrap">
            <a id="add_field_button", href="#", class="btn btn-default">Add More Fields</a>
            <div><input type="file" name="images[]" class="form-control"></div>
        </div>
      </div>
    </div>
  </div>
  </div>
  
  <div class="form-group" style="float: right">
  <div class="row">
    <div class="col-sm-4">
      <div class="actions">
        <button class="btn btn-white">저장</button>
      </div>
    </div>
    <div class="col-sm-2">
    <a href="<%= restaurants_path %>" class="btn btn-white">뒤로</a>
    </div>
  </div>
  </div>
<% end %>
</div>

<script type="text/javascript">
$("#add_field_button").on("click", function(e) {
    var max_fields      = 10; //maximum input boxes allowed
    var wrapper         = $(".input_fields_wrap"); //Fields wrapper
    var add_button      = $("#add_field_button"); //Add button ID
    
    var x = 1; //initlal text box count
    e.preventDefault();
     //on add input button click
    if(x < max_fields){ //max input box allowed
        $(wrapper).append('<div><input type="file" name="images[]" class="form-control"/><a href="#" class="remove_field">Remove</a></div>'); //add input box
          x++;
    }
    
    $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
        e.preventDefault(); $(this).parent('div').remove(); x--;
    })
});
</script>

app/views/restaurants/edit.html.erb
<div class="main">
	<section class="hgroup">
		<div class="container">
			<h2><%= t(:edit_restaurant)%> </h2>
		</div>
	</section>

	<section>
		<div class="container">
			<%= render 'form' %>
			<a class="btn btn-default" href="<%= restaurant_path(@restaurant) %>" role="button">식당으로 돌아가기</a>
		</div>
	</section>
</div>

app/views/restaurants/index.html.erb
<div class="main">

<section class="hgroup">
<div class="container">
<h2><%= t(:restaurant_list) %></h2>
</div>
</section>

<section>
<div class="container">
  <div class="row">
    <% @restaurants.each do |restaurant| %>
    <div class="col-sm-4" style="left:0px; top:0px;">
      <div class="restaurant_item">
      <a href="<%= restaurant %>">
        <%= image_tag restaurant.get_photo %></a>
        <div class="restaurant_name">
          <h4><%= link_to restaurant.name, restaurant %></h4>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
</section>
</div>

app/views/restaurants/new.html.erb
<head>
	<link type="text/css" href="css/bootstrap-timepicker.min.css" />
        <script type="text/javascript" src="js/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <script type="text/javascript" src="js/bootstrap-timepicker.min.js"></script>
</head>
<div class="main">

<section class="hgroup">
<div class="container">
<h2><%= t(:new_restaurant_html) %></h2>
</div>
</section>

<section>
<div class="container">
<%= render 'form' %>
</div>
</section>

</div>

app/views/restaurants/show.html.erb
<div class="main">

<section class="hgroup">
<div class="container">
<h2><%= @restaurant.name %></h2>
</div>
</section>

<section>
<div class="container">
<div class="row">

<div id="leftcol" class="col-md-6">
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% count = 0 %>
    <% @restaurant_photos.each do |p| %>
      <li data-target="#myCarousel" data-slide-to="<%=count%>"></li>
      <% count += 1 %>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag @restaurant.get_photo %>
    </div>
    <% @restaurant_photos.each do |r| %>
      <div class="item">
        <%= image_tag r.get_photo %>
      </div>
    <% end %>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<div id="sidebar" class="col-md-6">
<div class="row">
<table class="table table-bordered">
<thead>
</thead>
<tbody>
  <tr>
    <th>식당이름</th>
    <td><%= @restaurant.name %></td>
  </tr>
  <tr>
    <th>주소</th>
    <td><%= @restaurant.address %></td>
  </tr>
  <tr>
    <th>대표자</th>
    <td><%= @restaurant.Rep %></td>
  </tr>
  <tr>
    <th>전화번호</th>
    <td><%= @restaurant.phone_number %></td>
  </tr>
  <tr>
    <th>영업시간</th>
    <td><%= @restaurant.open_time %> ~ <%= @restaurant.close_time %></td>
  </tr>
  <tr>
    <th>기타정보</th>
    <td><%= @restaurant.extra_info %></td>
  </tr>
</tbody>
</table>
</div>

<div class="row" style="padding-bottom: 5px">
<a href="<%= restaurant_menus_path(@restaurant) %>" class="btn btn-lg btn-white">메뉴판 보기</a>
</div>

<div class="row">
  <% if current_user.nil? %>
    <a class="btn btn-white" href="<%= restaurants_path %>">식당 리스트로 돌아가기</a>
  <% elsif @restaurant.user_id == current_user.id %>
    <a class="btn btn-white" href="<%= new_restaurant_category_path(@restaurant) %>" role="button">카테고리 추가</a>
    <a class="btn btn-white" href="<%= edit_restaurant_path(@restaurant) %>">식당 정보 수정</a>
    <%= link_to '식당 삭제', @restaurant, method: :delete, data: { confirm: 'Are you suer?', class: "btn btn-white" } %>
  <% else %>
      <a class="btn btn-white" href="<%= restaurants_path %>">식당 리스트로 돌아가기</a>
  <% end %>
</div>
</div>

</div>
</div>
</section>