config/routes.rb
Rails.application.routes.draw do
  resources :carts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :exchange_rates
  resources :menu_photos
  resources :restaurants do
    resources :categories
    resources :menus
  end
  resources :currency_maps
  resources :language_maps
  resources :languages
  resources :restaurant_photos
  
  root 'restaurants#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :menu
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menus, dependent: :destroy
	belongs_to :restaurant

	def translation_category(locale)
		language_map = LanguageMap.find_by language_id: self.name_id, code: locale
		if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
	end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :menus
	has_many :exchange_maps, dependent: :destroy

	DEFAULT_EXCHANGES = "KRW"

	EXCHANGES = {
		"KRW" => "₩",
		"USD" => "$",
		"JPY" => "¥",
		"CNY" => "Y"
	}
end

app/models/currency_map.rb
class CurrencyMap < ActiveRecord::Base
  belongs_to :language
end

app/models/exchange_map.rb
class ExchangeMap < ActiveRecord::Base
	belongs_to :currency
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base

	def calculate(exchange_rate)
			exchangeRates = ExchangeRate.all
			krw_rate = exchangeRates.find_by(key: "KRW")
			usd_rate = exchangeRates.find_by(key: "USD")
			jpy_rate = exchangeRates.find_by(key: "JPW")
			cny_rate = exchangeRates.find_by(key: "CNY")

	end
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :language_maps, dependent: :destroy
	has_many :menus

	DEFAULT_LANGUAGE = "ko"
	
	LANGUAGES = {
		"ko" => "한국어",
		"en" => "English",
		"jp" => "日本語",
		"cn" => "中文"
	}

end

app/models/language_map.rb
class LanguageMap < ActiveRecord::Base
  belongs_to :language
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :category
  belongs_to :language
  belongs_to :currency
  belongs_to :restaurant
  has_many :menu_photos, dependent: :destroy
  has_many :carts

  def translation_name(locale)
  	language_map = self.language.language_maps.find_by_code(locale)
  	
  	if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
  end

  def translation_desc(locale)
    language_map = LanguageMap.find_by language_id: self.desc_id, code: locale
    
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def change_price(locale)
    exchange_map = ExchangeMap.find_by currency_id: self.currency_id, currency_code: locale
    if !exchange_map.nil?
      exchange_map.price
    else
      ""
    end
  end

  def translation_category(locale)
    if !self.category_id.nil?
      category = Category.find(self.category_id).name_id
      language_map = LanguageMap.find_by language_id: category, code: locale
    else
      ""
    end
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def get_mphoto
    mphoto = MenuPhoto.find_by menu_id: self.id
    if !mphoto.nil?
      mphoto.avatar.url(:medium)
    else
      "http://placehold.it/350x150?text=no+image"
    end
  end

end

app/models/menu_photo.rb
class MenuPhoto < ActiveRecord::Base
  belongs_to :menu

  has_attached_file :avatar,
   styles: { medium: "350x150>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :categories, dependent: :destroy
	has_many :restaurant_photos, dependent: :destroy

	def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/restaurant_photo.rb
class RestaurantPhoto < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :avatar,
   styles: { medium: "600x300>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/exchange_rates_controller.rb
class ExchangeRatesController < ApplicationController
  #before_action :set_exchange_rate, only: [:show, :edit, :update, :destroy]
  before_action :set_exchange_rate, except: [:index, :calculate, :new, :create]

  # GET /exchange_rates
  # GET /exchange_rates.json
  def index
    @exchange_rates = ExchangeRate.all
    
    respond_to do |format|
      format.html { render template: "exchange_rates/index.html.erb"}
      format.json { render :json => @exchange_rates }
    end 
  end

  # GET /exchange_rates/1
  # GET /exchange_rates/1.json
  

  def calculate
    exchange_usd = ExchangeRate.find_by(key: "USD");
    @rate_usd = exchange_usd.rate
    respond_to do |format|
      format.json { render json: {rate_usd: @rate_usd} }
    end 

  end

  # GET /exchange_rates/new
  def new
    @exchange_rate = ExchangeRate.new
  end

  # GET /exchange_rates/1/edit
  def edit
  end

  # POST /exchange_rates
  # POST /exchange_rates.json
  def create
    Currency::EXCHANGES.keys.each do |c|
      @exchange_rate = ExchangeRate.create(key: c, rate: params[c][:rate])
    end

    respond_to do |format|
      if @exchange_rate.save
        format.html { redirect_to @exchange_rate, notice: 'Exchange rate was successfully created.' }
        format.json { render :show, status: :created, location: @exchange_rate }
      else
        format.html { render :new }
        format.json { render json: @exchange_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exchange_rates/1
  # PATCH/PUT /exchange_rates/1.json
  def update
    respond_to do |format|
      if @exchange_rate.update(exchange_rate_params)
        format.html { redirect_to @exchange_rate, notice: 'Exchange rate was successfully updated.' }
        format.json { render :show, status: :ok, location: @exchange_rate }
      else
        format.html { render :edit }
        format.json { render json: @exchange_rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exchange_rates/1
  # DELETE /exchange_rates/1.json
  def destroy
    @exchange_rate.destroy
    respond_to do |format|
      format.html { redirect_to exchange_rates_url, notice: 'Exchange rate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exchange_rate
      @exchange_rate = ExchangeRate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exchange_rate_params
      params.require(:exchange_rate).permit(:key, :rate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/exchange_rates_helper.rb
module ExchangeRatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/menu_photos_helper.rb
module MenuPhotosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/exchange_rates/_form.html.erb
<%= form_for(@exchange_rate) do |f| %>
  <% if @exchange_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exchange_rate.errors.count, "error") %> prohibited this exchange_rate from being saved:</h2>

      <ul>
      <% @exchange_rate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-2">
  <% Currency::EXCHANGES.each_pair do |k, v| %>
  <div class="form-group">
    <label for="<%= v %>_rate">환율(<%=v%>)</label>
    <input type="text" class="form-control" id="<%= k %>" name="<%= k %>[rate]">/1000원
  </div>
  <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exchange_rates/edit.html.erb
<h1>Editing Exchange Rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @exchange_rate %> |
<%= link_to 'Back', exchange_rates_path %>

app/views/exchange_rates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exchange Rates</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exchange_rates.each do |exchange_rate| %>
      <tr>
        <td><%= exchange_rate.key %></td>
        <td><%= exchange_rate.rate %></td>
        <td><%= link_to 'Show', exchange_rate %></td>
        <td><%= link_to 'Edit', edit_exchange_rate_path(exchange_rate) %></td>
        <td><%= link_to 'Destroy', exchange_rate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exchange rate', new_exchange_rate_path %>

app/views/exchange_rates/new.html.erb
<h1>New Exchange Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', exchange_rates_path %>

app/views/exchange_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @exchange_rate.key %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @exchange_rate.rate %>
</p>

<%= link_to 'Edit', edit_exchange_rate_path(@exchange_rate) %> |
<%= link_to 'Back', exchange_rates_path %>