config/routes.rb
Rails.application.routes.draw do
  resources :carts
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :exchange_rates
  resources :menu_photos
  resources :restaurants do
    resources :categories
    resources :menus
  end
  resources :currency_maps
  resources :language_maps
  resources :languages
  resources :restaurant_photos
  
  root 'restaurants#index'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	belongs_to :user
	belongs_to :menu
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :menus, dependent: :destroy
	belongs_to :restaurant

	def translation_category(locale)
		language_map = LanguageMap.find_by language_id: self.name_id, code: locale
		if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
	end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
	has_many :menus
	has_many :exchange_maps, dependent: :destroy

	DEFAULT_EXCHANGES = "KRW"

	EXCHANGES = {
		"KRW" => "₩",
		"USD" => "$",
		"JPY" => "¥",
		"CNY" => "Y"
	}
end

app/models/currency_map.rb
class CurrencyMap < ActiveRecord::Base
  belongs_to :language
end

app/models/exchange_map.rb
class ExchangeMap < ActiveRecord::Base
	belongs_to :currency
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base

	def calculate(exchange_rate)
			exchangeRates = ExchangeRate.all
			krw_rate = exchangeRates.find_by(key: "KRW")
			usd_rate = exchangeRates.find_by(key: "USD")
			jpy_rate = exchangeRates.find_by(key: "JPW")
			cny_rate = exchangeRates.find_by(key: "CNY")

	end
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :language_maps, dependent: :destroy
	has_many :menus

	DEFAULT_LANGUAGE = "ko"
	
	LANGUAGES = {
		"ko" => "한국어",
		"en" => "English",
		"jp" => "日本語",
		"cn" => "中文"
	}

end

app/models/language_map.rb
class LanguageMap < ActiveRecord::Base
  belongs_to :language
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :category
  belongs_to :language
  belongs_to :currency
  belongs_to :restaurant
  has_many :menu_photos, dependent: :destroy
  has_many :carts

  def translation_name(locale)
  	language_map = self.language.language_maps.find_by_code(locale)
  	
  	if !language_map.nil?
  		language_map.lan_text
  	else
  		""
  	end
  end

  def translation_desc(locale)
    language_map = LanguageMap.find_by language_id: self.desc_id, code: locale
    
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def change_price(locale)
    exchange_map = ExchangeMap.find_by currency_id: self.currency_id, currency_code: locale
    if !exchange_map.nil?
      exchange_map.price
    else
      ""
    end
  end

  def translation_category(locale)
    if !self.category_id.nil?
      category = Category.find(self.category_id).name_id
      language_map = LanguageMap.find_by language_id: category, code: locale
    else
      ""
    end
    if !language_map.nil?
      language_map.lan_text
    else
      ""
    end
  end

  def get_mphoto
    mphoto = MenuPhoto.find_by menu_id: self.id
    if !mphoto.nil?
      mphoto.avatar.url(:medium)
    else
      "http://placehold.it/350x150?text=no+image"
    end
  end

end

app/models/menu_photo.rb
class MenuPhoto < ActiveRecord::Base
  belongs_to :menu

  has_attached_file :avatar,
   styles: { medium: "350x150>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :menus
	has_many :categories, dependent: :destroy
	has_many :restaurant_photos, dependent: :destroy

	def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/restaurant_photo.rb
class RestaurantPhoto < ActiveRecord::Base
  belongs_to :restaurant

  has_attached_file :avatar,
   styles: { medium: "600x300>", thumb: "100x100>" },
   default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def get_photo
		rphoto = RestaurantPhoto.find_by restaurant_id: self.id
		if !rphoto.nil?
			rphoto.avatar.url(:medium)
		else
			"http://placehold.it/350x150?text=no+image"
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :carts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_restaurant
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = @restaurant.categories.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    
  end

  # GET /categories/new
  def new
    @category = @restaurant.categories.new
  end

  # GET /categories/1/edit
  def edit
    @category = @restaurant.categories.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create

    language_category = Language.create
    Language::LANGUAGES.keys.each do |l|
      if !params[l].blank? && !params[l][:name].blank?
        language_category.language_maps.create(code: l, lan_text: params[l][:name])
      end
    end    

    @category = @restaurant.categories.new(name_id: language_category.id, restaurant_id: params[:restaurant_id])

    respond_to do |format|
      if @category.save
        format.html { redirect_to [@category.restaurant], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    language_category = Language.find(@category.name_id)
    Language::LANGUAGES.keys.each do |l|
      if !params[l].blank? && !params[l][:name].blank?
        language_map = LanguageMap.find_by language_id: language_category, code: l
        if !language_map.nil?
          language_map.update_column(:lan_text, params[l][:name])
        end
      end
    end
    respond_to do |format|
      if !language_category.nil?
        format.html { redirect_to [@category.restaurant, @categories], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    language = Language.find(@category.name_id)
    language.destroy
    respond_to do |format|
      format.html { redirect_to [@category.restaurant], notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/menu_photos_helper.rb
module MenuPhotosHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/categories/_form.html.erb
<%= form_for([@restaurant, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="col-sm-3">
  <% Language::LANGUAGES.each_pair do |key, value| %>
    <div class="form-group">
      <label for="<%= key %>_name">카테고리명(<%= value %>)</label>
      <input type="text" class="form-control" 
        id="<%= key %>_name" name="<%= key %>[name]">
    </div>
  <% end %>
  </div>
  </div>

  <div class="row" style="float: right">
  <div class="col-sm-3">
  <div class="actions">
    <button class="btn btn-white">
      저장
    </button>
  </div>
  </div>
  <div class="col-sm-2">
  <a class="btn btn-white" href="<%= restaurant_path(@category.restaurant) %>" role="button">식당으로 돌아가기</a>
  </div>
  </div>
<% end %>

app/views/categories/_index.html.erb
<h1><%= t(:category) %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.translation_category(session[:user_language]) %></td>
        <td><%= link_to '수정', edit_restaurant_category_path(category.restaurant, category) %></td>
        <td><%= link_to '삭제', [category.restaurant, category] ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a class="btn btn-primary" href="<%= new_restaurant_category_path(@restaurant) %>" role="button">카테고리 추가</a>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<a class="btn btn-default" href="<%= restaurant_path(@category.restaurant) %>" role="button">식당으로 돌아가기</a>

app/views/categories/new.html.erb
<div class="main">
<section class="hgroup">
<div class="container">
<h2><%=t(:new_category)%></h2>
</div>
</section>

<section>
<div class="container">
<%= render 'form' %>
</div>
</section>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @category.translation_category(session[:user_language]) %>
</p>

<%= link_to '수정', edit_restaurant_category_path(@category.restaurant, @category) %> |
<%= link_to '식당으로 돌아가기', restaurant_path(@category.restaurant) %>